### ISSUE TITLE
Support for multiple application within one project

### ISSUE THREAD

**Issue by ph55** [NativeScript/nativescript-schematics#25]
[V] Feature request

Currently angular-cli allows to create and serve multiple applications inside one repository and share code across these applications.
But nativescript only allows to create one application.

Do you guys plan to allow nativescript app to be added as angular cli project/application? (`ng generate application`).

Lets say we have existing angular cli repository with 2 or more web applications. And we want to add nativescript app to build mobile UI for one of them.

With current schematics it's not possible.

Please allow to do something similar.
* Add nativescript application to current angular cli repository:
 `ng generate application -c=@nativescript/schematics --name=my-nativescript-app`

* Run `tns` by application name
`tns run ios --app=my-nativescript-app`

Read more: https://github.com/angular/angular-cli/wiki/stories-multiple-apps

**Comment by sebawita** [comment]
hi @ph55,
This sounds like a nice feature. I will do some research around it to see how to make it work.

Do you have any suggestions as to what should happen when you run `ng generate application -c=@nativescript/schematics --name=my-nativescript-app`?

**Comment by JonnyBGod** [comment]
I would also prefer this approach instead of a "shared app".
Most of the times the Mobile app we need should be different from the web app, usually more specific usage and striped from a bunch of extra web features.

Also this should be much easier to implement as we just need a simple way to create and run a NS project.

Check out [xplat](https://nstudio.io/xplat/) for some inspiration.

**Comment by Gitelaus** [comment]
Below project is using the "ng new -c=@nativescript/schematics --shared APP_NAME` method, meaning it's a shared project structure.

After jimmying my project into a workable structure (move `src` into a project directory instead, point `angular.json` stuff at that directory, etc.) I needed a way of managing more than one nativescript project.

I did originally try to edit the `webpack.config.js` that is generated at the root level, but found various issues that eventually made this a non-viable workaround.

In the end, I am simply running a `js` file to load the `nsconfig.json`, edit the `appPath` and then save the file. This, with the package.json scripts (see below) means I am now able to pick which project to run.

Script can be found here.

https://gist.github.com/Gitelaus/9f318f7328664ac7ed60d30e278a7c8f

Of course, this small script has a dependency (minimist for arg parsing) but you can drop that out and so some string parsing to achieve the same effect.

**Comment by JonnyBGod** [comment]
We are close to a year since this came up, any news about supporting multiple projects?

This should be the top priority in my opinion. The current schematics are basically useless for proper projects.

The common knowledge these days and after a lot of trial and error from a lot of different teams and communities is that to achieve good code share for cross platform projects we should focus on sharing business logic and not views / components.

The current implementation leads to a mess once a project grow bigger than a proof of concept and in general does not even make any sense to try to replicate a full application on multiple platforms because on most cases the applications should actually be different, with different focus and set of functionalities, not even going to discuss the native feel that apps should have for each platform.

Is this going to be properly considered by this team or should we move on and create a new project?
Either way is fine, we just need to get out of this limbo where nothing happens for a year.

**Comment by armackey** [comment]
Not sure if I'm in the right place but would this cover server side rendering? I added nativescript to an angular universal app and I can no longer run `npm run build:ssr && npm run serve:ssr`.

Keep getting - 
`ERROR in : Type AppComponent in app.component.ts is part of the declarations of 2 modules: AppModule`

**Comment by fofaria** [comment]
i agree with @JonnyBGod, the current way of sharing code, on large enterprise applications, is a recipe for disaster. is there any news about this feature? or if you don't have idea when it's going to be implemented, do you recommend using [xplat](https://nstudio.io/xplat) for example? 

thank you.

**Comment by sebawita** [comment]
hi @JonnyBGod and @fofaria,
these schematics are designed for projects where there is a significant overlap around the functionality and the views that are displayed. They don't necessarily have to be the same, but most of the views should be trying to provide with similar functionality.

When it comes to building projects where you share some of the business logic, but most of the views are different, or even when you want to have multiple web/mobile apps then I would probably go with 
 [xplat](https://nstudio.io/xplat), as suggested by @fofaria 

Note, this is not about proper or not proper projects. There are different type of projects and requirements. This project tries to solve one specific type of projects.

**Comment by Lightk3ira** [comment]
Hey everyone, has this issue been addressed? In my opinion it seems to be a very beneficial addition to add. as well as creating a nativescript + Angular library that I also raised coming close to a year ago now. Both seem very important for large scale multiple projects. I am just wondering if the Nativescript team is actually working on any of these features? They say they are in different comments but like..getting close to a year.

**Comment by MyFoodOrder** [comment]
Hello, i also think this is a must have , i just run into this issue when trying to solve the problem of shared code between angular web projects and nativescript project

**Comment by Dyloneus** [comment]
Just adding my voice to this request. The idea of creating, running and managing multiple nativescript projects in a unified solution has a tonne of benefits that I would love to see out in the wild.
Thanks
