### ISSUE TITLE
Dependency @nativescript/schematics is added twice

### ISSUE THREAD

**Issue by d-koppenhagen** [NativeScript/nativescript-schematics#279]
**Environment**
Provide the content of the `package.json` file in the project:

**Describe the bug**
Adding the schematics causes a dependency of `@nativescript/schematics` in both: `dependencies` and `devDependencies` but with different versions.
There should't be a direct dependency but a devDependency with the correct version.

```json
"dependencies": {
    ...
    "@nativescript/schematics": "^9.0.0",
    ...
  },
"devDependencies": {
    ...
    "@nativescript/schematics": "~2.0.0",
    ...
}
```

This should be respected as well by the migration scripts I think @NathanWalker  

**To Reproduce**
- Open an existing Angular Project (Angular 9.x.x)
- Exec: `ng add @nativescript/schematics --skipAutoGeneratedComponent`
- check your `package.json`

**Expected behavior**

The `package.json` should just contain a single devDependency for `@nativescript/schematics` within it's version `9.x.x`.

This can be accomplished by adding the following to the `package.json` since Angular 9.0.0 or greater.

```
"ng-add": {
    "save": "devDependencies"
  },
```

Manual injections for the dependency and devDependency should be removed, either `2.0.0` and `9.0.0`.

**Comment by zaccanoy** [comment]
This may be fixed in master, but there isn't a 9.x release on NPM that removes the `@angular/http` dependency and updates the `@nativescript/schematics` dependency. Anyone who wishes to create a new shared project has to install the package from the GitHub repository, and even then I was experiencing some issues with the Webpack configuration.
